export { default as rap } from './rap'
export { default as proxy } from './proxy'
export { default as magixCombine } from './magix-combine'
export { default as rapVerify } from './rap-verify'
export { default as rewriteExtension } from './rewrite-extension'

export { default as magixDesiger } from './injects/magix-desiger'
export { default as crossConfigs } from './injects/cross-configs'
export { default as devEnv } from './injects/dev-env'
export { default as magixInspector } from './injects/magix-inspector'
export { default as webSprite } from './injects/web-sprite/index'
export { default as magixHmr } from './injects/magix-hmr/index'
