export { default as rap } from './rap'
export { default as proxy } from './proxy'
export { default as magixAnalyse } from './magix-combine'
export { default as rapVerify } from './rap-verify'
export { default as rewriteExtension } from './rewrite-extension'

export { default as magixDesigerInject } from './injects/magix-desiger'
export { default as crossConfigsInject } from './injects/cross-configs'
export { default as devEnvInject } from './injects/dev-env'
export { default as magixInspectorInject } from './injects/magix-inspector'
export { default as webSpriteInject } from './injects/web-sprite/index'
export { default as magixHmrInject } from './injects/magix-hmr/index'
